export class UCIFormat {
    /*!
     * Default
     */
    static UCIFormatUnknown :number = 0;
    /*!
     * UCI generated by Ingenico
     */
    static UCIFormatIngenico :number = 1;

    /**
     * Returns the value to the response code by code number
     *
     * @param code The number of the code to check against
     */
    static getFormatByNumber(code: number) {
        let responseValue = 'UCIFormatUnknown';
        for (let prop in this) {
            if (typeof this[prop] === 'number' && this[prop] === code) {
                responseValue = prop;
                break;
            }
        }
        return responseValue;
    }
}
